package facade;

public enum TypeRole {
    SCIENTIFIQUE,
    CHERCHEUSE,
    REPARTITEUR,
    MEDECIN,
    EXPERT_AUX_OPERATIONS,
    PLANIFICATEUR_DURGENCE,
    SPECIALISTE_EN_MISE_EN_QUARENTAINE,
}
